### ISSUE TITLE
Dois branches feature-felipe

### ISSUE THREAD

**Issue by 5putnik** [thaynamorim/discreta02g01#10]
Tem dois branches feautre-felipe. Não sei qual dos dois você está atualizando, mas, por favor, mantenha apenas um. O padrão no nosso grupo é com a letra minúscula, mas eu não me incomodo (e creio que nenhum membro se incomodaria) se você preferir manter o feature-Felipe (com letra maiúscula). De qualquer forma, escolha o que não está atualizado e delete, por favor.
![Erro](https://cloud.githubusercontent.com/assets/13878835/9702497/67a55d10-5436-11e5-9922-7252ceb7328a.jpg)

**Comment by felipecalado** [comment]
Feito.
