### ISSUE TITLE
Preenchimento do Doxygen 

### ISSUE THREAD

**Issue by thaynamorim** [thaynamorim/discreta02g01#6]
O Doxygen precisa ter os autores, detalhamento dos autores e do programa e das funções. Como não terminamos ainda de desenvolver as funções, pode documentar só as que existem agora. 
https://www.dropbox.com/sh/8xsunikpo5qhhoc/AAD_DzCa3nxFaIhGGn5g2pIPa/10-msg-doxygen.txt?dl=0 pra quem tiver com dificuldade.

**Comment by 5putnik** [comment]
Documentado.
