### ISSUE TITLE
Adicionar arquivo README

### ISSUE THREAD

**Issue by thaynamorim** [thaynamorim/discreta02g01#7]
O arquivo README.md, dentro do Github, precisa utilizar a sintaxe Markdown.

**Comment by drbeco** [comment]
O README.md é um arquivo que fica disponível visivelmente na página inicial do seu projeto no github.

Assim, quem chegar até seu programa, a primeira coisa que lê é o README.md.

Veja exemplos de readme's em vários programas hospedados aqui.
- https://github.com/SWI-Prolog/swipl-devel
- https://github.com/drbeco/doxygenprolog
- https://github.com/mailpile/Mailpile
- https://github.com/FoolCode/Plugin

**Comment by 5putnik** [comment]
Adicionado.
